### ISSUE TITLE
Update according to isodoc changes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-csd#4]
* isodoc title is now isolocalizedtitle (gbdoc title is inherited)
* bibliography now takes multiple dates in one array

**Comment by ronaldtse** [comment]
Related to https://github.com/riboseinc/isodoc-models/issues/36 , in CalConnect we (still) have "Provisional Committee" instead of "Project Committee", so this change is to be kept in mind.

**Comment by opoudjis** [comment]
The riboseinc/isodoc-models#36 updates going to be considered under that ticket, as will preventing their propagation into CSD.

**Comment by opoudjis** [comment]
Diagram updated according to current grammar.
