### ISSUE TITLE
StarUML to PlantUML diagrams

### ISSUE THREAD

**Issue by VasBu** [metanorma/metanorma-model-csd#5]
Convert metanorma CSD StarUML diagrams to PlantUML diagrams

**Comment by VasBu** [comment]
@ronaldtse , please find the zip archives that include the results of conversion.
- [PNG.zip](https://github.com/riboseinc/metanorma-model-csd/files/2317194/PNG.zip)
- [Source Files.zip](https://github.com/riboseinc/metanorma-model-csd/files/2317195/Source.Files.zip)
- [SVG.zip](https://github.com/riboseinc/metanorma-model-csd/files/2317196/SVG.zip)

**Comment by VasBu** [comment]
@ronaldtse , new version 1.1, small update of a enumeration type (+ prefix has been removed)

- [PNG.zip](https://github.com/riboseinc/metanorma-model-csd/files/2338879/PNG.zip)
- [Source Files.zip](https://github.com/riboseinc/metanorma-model-csd/files/2338880/Source.Files.zip)
- [SVG.zip](https://github.com/riboseinc/metanorma-model-csd/files/2338881/SVG.zip)

**Comment by ronaldtse** [comment]
Done in 8a3a2ad0599b27c2e767d865c008b75d49c36440. Thanks @VasBu !
