### ISSUE TITLE
Including contributors and their roles in CSD

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-csd#6]
CSD documents should allow specification of contributors. Supplement this to the models.

Similar to https://github.com/riboseinc/metanorma-model-ogc/issues/2

**Comment by opoudjis** [comment]
Please say what you actually need. I am only going to implement personal contributors, and editor vs author status, as has been implemented in OGC.

**Comment by opoudjis** [comment]
There is absolutely nothing to add to the model, since the relaton model already permits any contributor to be either a person or an organisation.

**Comment by opoudjis** [comment]
You have not provided any guidance as to how these contributors will be displayed in the document. I am going to dump them somewhere on the title page; you will need to review whether that's what you want.

**Comment by opoudjis** [comment]
@ronaldtse Please review.

[flintstones.zip](https://github.com/riboseinc/metanorma-model-csd/files/2615128/flintstones.zip)

**Comment by opoudjis** [comment]
Overlaps with https://github.com/riboseinc/metanorma-csd/issues/71

@ronaldtse, do I close this ticket?

**Comment by ronaldtse** [comment]
Let's close this. We will need another ticket to "prettify" the authorship but we need some design thought on that.

**Comment by ronaldtse** [comment]
Actually, reopening this ticket -- can we "dynamically" loop through the roles, so that if we add a role in the future, the CSD template won't need updating?

**Comment by opoudjis** [comment]
I will display the roles found in alphabetic order.

**Comment by opoudjis** [comment]
Took me a while to get it right, but I finally have.
